services:
  - type: web
    name: stravanalytics
    runtime: docker
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stravanalytics-db
          property: connectionString
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: BASE_URL
        sync: false

databases:
  - name: stravanalytics-db
    databaseName: stravanalytics
    plan: free
